name: ehidrive
description: App will allow EHI employees to store files on EHI server and synchronize across devices and share files

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  # flutter_launcher_icons: ^0.7.5
  flutter_bloc: ^6.0.1
  modal_bottom_sheet: ^0.2.0+1
  receive_sharing_intent: ^1.4.0+2
  image_picker: ^0.6.7+4
  pin_entry_text_field: ^0.1.4
  flushbar: ^1.10.4
  pinput: ^0.2.4
  device_info: ^0.4.2+4
  shared_preferences: ^0.5.8
  xml: ^4.1.0
  http: ^0.12.2
  splashscreen: ^1.2.0
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

dev_dependencies:
  # flutter_test:
  #   sdk: flutter

# flutter_icons:
#   android: "launcher_icon"
#   ios: true
#   image_path: "assets/ehidrive-logo.png"

flutter:

  uses-material-design: true
  assets:
    - assets/